version: '3.3'
services:
  mysql:
    container_name: mysql-app
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"

  redis:
    container_name: redis-app
    image: redis:latest
    restart: always
    environment:
      REDIS_PASSWORD: your_redis_password
    ports:
      - "6379:6379"

  golang-app:
    container_name: chatbot-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    ports:
      - "5067:5067"
    environment:
      APP_PORT: "5067"
      DB_HOST: mysql-app
      DB_PORT: "3306"
      DB_USERNAME: your_user
      DB_PASSWORD: your_password
      DB_NAME: your_database
      REDIS_HOST: redis-app
      REDIS_PORT: "6379"
      REDIS_PASSWORD: your_redis_password
      REDIS_USERNAME: default
      OPEN_AI_TOKEN: ${OPEN_AI_TOKEN}
