version: '3.3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: chatbot_db
      MYSQL_USER: fadilah
      MYSQL_PASSWORD: typ123000
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    restart: always
    environment:
      REDIS_PASSWORD: your_redis_password
    ports:
      - "6379:6379"

  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
    ports:
      - "5067:5067"
    environment:
      APP_PORT: "5067"
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USERNAME: fadilah
      DB_PASSWORD: typ123000
      DB_NAME: chatbot_db
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_PASSWORD: your_redis_password
      REDIS_USERNAME: default
      OPEN_AI_TOKEN: ${OPEN_AI_TOKEN}
