version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
    ports:
      - "5076:5076"
    environment:
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USERNAME: your_user
      DB_PASSWORD: your_password
      DB_NAME: your_database
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      OPEN_AI_TOKEN: ${OPEN_AI_TOKEN}
